kind = "web"
previewPath = "/"
title = "BMT Decor V2"
version = "1.0.0"
id = "artifacts/bmt-decor"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26090

[services.development]
run = "pnpm --filter @workspace/bmt-decor run dev"

[services.env]
PORT = "26090"
BASE_PATH = "/"
